# Generated by Django 4.2.7 on 2024-11-07 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasker', '0002_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('task_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('deadline_time', models.DateTimeField()),
                ('priority', models.PositiveSmallIntegerField()),
                ('readiness', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_task_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasker.task')),
                ('foreign_user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasker.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(through='tasker.User_Task', to='tasker.task'),
        ),
    ]
